development:
  adapter: mysql2
  database: time_tracker_dev
  host: localhost
  username: root
  password:

test: &test
  adapter: mysql2
  database: time_tracker_test
  host: localhost
  username: root
  password: 
 
production:
  adapter: mysql2
  database: time_tracker_production
  host: localhost
  username: root
  password: 
  
 

cucumber:
  <<: *test